{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dockercoins.serviceAccountName" . }}
  labels:
{{ include "dockercoins.labels" . | indent 4 }}
{{- end -}}
