apiVersion: {{ .Values.apiVersionService }}
kind: Service
metadata:
  name: {{ .Values.image.rng }}
  namespace: {{ .Values.namespaces }}
  labels:
    servicename: {{ .Values.image.rng }}
{{ include "dockercoins.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.typeC }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    servicename: {{ .Values.image.rng }}
