apiVersion: {{ .Values.apiVersionService }}
kind: Service
metadata:
  name: {{ .Values.image.webui }}
  namespace: {{ .Values.namespaces }}
  labels:
    servicename: {{ .Values.image.webui }}
{{ include "dockercoins.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.typeN }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    servicename: {{ .Values.image.webui }}
